# Generated by Django 3.2.10 on 2021-12-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='damaged',
            field=models.BooleanField(default=False),
        ),
    ]
