# Generated by Django 3.2.10 on 2021-12-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211225_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperlink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
